name: Build and Publish Binaries

on: push

jobs:
  draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release create --draft "${{ github.sha }}" --title "Build ${{ github.sha }}"

  build:
    name: Build for ${{ matrix.os }}
    needs: draft-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
        - name: linux
          os: ubuntu-latest
          collector-artifact: target/release/clique-collector
          collector-name: clique-collector-linux
          api-artifact: target/release/clique-api
          api-name: clique-api-linux
        - name: windows
          os: windows-latest
          collector-artifact: target/release/clique-collector.exe
          collector-name: clique-collector.exe
          api-artifact: target/release/clique-api.exe
          api-name: clique-api.exe
        - name: macos
          os: macos-latest
          collector-artifact: target/release/clique-collector
          collector-name: clique-collector-macos
          api-artifact: target/release/clique-api
          api-name: clique-api-macos

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        mv ${{ matrix.collector-artifact }} ${{ matrix.collector-name }}
        mv ${{ matrix.api-artifact }} ${{ matrix.api-name }}
        gh release upload "${{ github.sha }}" ${{ matrix.collector-name }} ${{ matrix.api-name }}

  publish:
    name: Publish release with binaries
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Publish release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit --draft=false "${{ github.sha }}"
